export const StudentList = [  
    {  
      userId:'1', 
      name:'Jose',
      lastname:'Perez',
      gender:'M',
      Math: 15,
      English: 10,
      Literature: 12,
    },
    {  
      userId:'2', 
      name:'Karla',
      lastname:'Juarez',
      gender:'F',
      Math: 12,
      English: 16,
      Literature: 5,
    },
    {  
      userId:'3', 
      name:'Carlos',
      lastname:'Guarda',
      gender:'M',
      Math: 9,
      English: 8,
      Literature: 5,
    },
    {  
      userId:'4', 
      name:'Giancarlos',
      lastname:'Requejo',
      gender:'F',
      Math: 15,
      English: 16,
      Literature: 20,
    },
    {  
      userId:'5', 
      name:'Karen',
      lastname:'Silva',
      gender:'F',
      Math: 10,
      English: 16,
      Literature: 16,
    },
    {  
      userId:'6', 
      name:'Rosemery',
      lastname:'Mendoza',
      gender:'F',
      Math: 12,
      English:10,
      Literature: 5,
    },
    {  
      userId:'7', 
      name:'Rafael',
      lastname:'Martinez',
      gender:'M',
      Math: 12,
      English: 16,
      Literature: 5,
    },
    {  
      userId:'8', 
      name:'Maricielo',
      lastname:'Benedicto',
      gender:'F',
      Math: 12,
      English: 16,
      Literature:15,
    },
    {  
      userId:'3', 
      name:'Karla',
      lastname:'Juarez',
      gender:'F',
      Math: 12,
      English: 16,
      Literature:19,
    },
    {  
      userId:'3', 
      name:'Pedro',
      lastname:'Vertiz',
      gender:'M',
      Math: 20,
      English: 19,
      Literature: 19,
    },
    {  
      userId:'3', 
      name:'Marco',
      lastname:'Ccorisoncco',
      gender:'M',
      Math: 15,
      English: 16,
      Literature: 12,
    },
    {  
      userId:'3', 
      name:'Cinthia',
      lastname:'Yoshida',
      gender:'F',
      Math: 12,
      English: 16,
      Literature: 5,
    },
    {  
      userId:'3', 
      name:'Ada',
      lastname:'Stephano',
      gender:'F',
      Math: 12,
      English: 16,
      Literature: 5,
    },
    {  
      userId:'3', 
      name:'Luis Miguel',
      lastname:'Lopez',
      gender:'M',
      Math: 20,
      English: 15,
      Literature: 18,
    },
 ]